server:
  port: 7002
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - AuthenticationFilter
      routes[0]:
        id: discovery-server
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
        uri: http://localhost:7000
      routes[1]:
        id: catalog-service
        predicates[0]: Path=/catalog-service/api/v1/products/**
        uri: lb://catalog-service
